import "server-only";
import { createHash } from "node:crypto";
import { createAdminClient } from "@/lib/supabase/admin";
import { rayaComplete } from "@/lib/raya/llm";
import { LOCALES, type Locale } from "@/lib/locale";

/**
 * Translating an EXPORT, which is a different job from generating one.
 *
 * The economics are the whole reason this exists. Offering a report in four
 * languages the obvious way means generating it four times — each pass carrying
 * the source lesson, the roster, the Kernel profile back into context, and each
 * pass free to reach a different conclusion, so the "same" report in French
 * quietly says something the English one did not. Translating instead costs one
 * short call over text we already have, and guarantees the four documents say
 * the same thing because three of them are derived from the first.
 *
 * Then it is cached content-addressed, which is where the saving actually lands:
 * a summary of the same lesson generated by thirty students in a class collapses
 * to one translation per language for the entire class.
 */

export type TranslatableDoc = { title: string; meta?: string | null; body: string };

/** Locales we will translate into — the four the product already ships. */
export function isSupportedLocale(v: unknown): v is Locale {
  return typeof v === "string" && LOCALES.some((l) => l.code === v);
}

/**
 * The cache key.
 *
 * Over the CONTENT, not a document id. Two teachers exporting the same class
 * report share a row; a report that changes gets a new key and the stale row is
 * simply never asked for again, so there is no invalidation to get wrong.
 */
export function documentHash(doc: TranslatableDoc): string {
  return createHash("sha256")
    .update(`${doc.title}\n${doc.meta ?? ""}\n${doc.body}`, "utf8")
    .digest("hex");
}

/** Refuse to spend a model call on something that is not a document. */
export const MAX_DOC_CHARS = 40_000;

const SYSTEM = `You translate a study document. You are not writing one.

RULES
- Translate the title, the optional meta line, and the body into {LANGUAGE}.
- Preserve the Markdown EXACTLY: heading levels, list markers, bold, tables,
  blank lines. The output is typeset by an exporter that reads this structure.
- Preserve every number, score, percentage, date and name unchanged.
- Do NOT translate: "Bluestift", "Raya", "Kernel", "Rooms", "Tools", "Schools".
  They are product names.
- Do NOT summarise, expand, correct, reorder or comment. A translation that
  improves the document is a wrong translation: the reader is comparing it with
  the original.
- If a passage is already in {LANGUAGE}, leave it as it is.

OUTPUT
Return ONLY this, with no preamble and no code fence:
TITLE: <translated title>
META: <translated meta, or an empty line if there was none>
---
<translated body>`;

function parseResponse(text: string, fallback: TranslatableDoc): TranslatableDoc {
  // Defensive by default: a model that ignores the format must degrade to the
  // untranslated document, never to a mangled one. A reader who gets the
  // original back has lost a feature; one who gets a half-parsed document has
  // lost the report.
  const cleaned = text.replace(/^```[a-z]*\n?/i, "").replace(/\n?```$/, "").trim();
  const split = cleaned.indexOf("\n---");
  if (split === -1) return fallback;

  const head = cleaned.slice(0, split);
  const body = cleaned.slice(split + 4).replace(/^\n+/, "");
  const title = /^TITLE:\s*(.*)$/m.exec(head)?.[1]?.trim();
  const meta = /^META:\s*(.*)$/m.exec(head)?.[1]?.trim();
  if (!title || !body.trim()) return fallback;

  return { title, meta: meta || null, body };
}

/**
 * Translate a document, serving a cached translation when one exists.
 *
 * Never throws and never returns null: on any failure the SOURCE document comes
 * back with `translated: false`, so the caller always has something to download.
 * The alternative — an error where a download was expected — turns a missing
 * nicety into a broken export.
 */
export async function translateDocument(
  doc: TranslatableDoc,
  locale: Locale,
): Promise<{ doc: TranslatableDoc; translated: boolean; cached: boolean }> {
  const hash = documentHash(doc);
  const admin = createAdminClient().schema("learning");

  try {
    const { data } = await admin
      .from("document_translations")
      .select("title, meta, body")
      .eq("source_hash", hash)
      .eq("locale", locale)
      .maybeSingle();
    if (data) {
      // Best-effort usage stamp: it informs pruning later and must never be
      // allowed to fail the read it decorates.
      void admin
        .from("document_translations")
        .update({ last_used_at: new Date().toISOString() })
        .eq("source_hash", hash)
        .eq("locale", locale)
        .then(() => undefined);
      return {
        doc: { title: data.title, meta: data.meta, body: data.body },
        translated: true,
        cached: true,
      };
    }
  } catch {
    // A cache miss and a cache outage are the same thing to the caller: we pay
    // for the call. Falling over here would make the cache a liability.
  }

  const language = LOCALES.find((l) => l.code === locale)?.englishName ?? "English";
  let out: TranslatableDoc;
  try {
    // `fast` on purpose. This is a mechanical transformation over text that is
    // already written — the deep tier buys nothing here and costs several times
    // as much, which would undercut the entire point of the feature.
    const { text } = await rayaComplete(
      [
        { role: "system", content: SYSTEM.replaceAll("{LANGUAGE}", language) },
        {
          role: "user",
          content: `TITLE: ${doc.title}\nMETA: ${doc.meta ?? ""}\n---\n${doc.body}`,
        },
      ],
      "fast",
    );
    out = parseResponse(text, doc);
  } catch {
    return { doc, translated: false, cached: false };
  }

  if (out === doc) return { doc, translated: false, cached: false };

  try {
    await admin.from("document_translations").upsert(
      {
        source_hash: hash,
        locale,
        title: out.title,
        meta: out.meta ?? null,
        body: out.body,
      },
      { onConflict: "source_hash,locale" },
    );
  } catch {
    // The translation is good; only the saving of it failed. Serve it — the
    // next reader pays again, which is a cost, not a fault.
  }

  return { doc: out, translated: true, cached: false };
}
