"use client";

import { useEffect, useState } from "react";
import type { ClassInsight, SchoolSubject, Simulation } from "@/lib/school-admin";
import { useAppTheme } from "@/components/ui/theme";
import { netFetch, getJsonCached, invalidateCached } from "@/lib/net/client-fetch";
import { DocumentActions } from "@/components/ui/doc-actions";
import { panelCard, textInput, ctaButton } from "@/components/ui/forms";
import { type BrandedDoc } from "@/lib/document";
import { useTranslate } from "@/components/ui/locale";
import type { MessageKey } from "@/lib/i18n";

const pct = (v: number | null) => (v == null ? "—" : `${Math.round(v * 100)}%`);

type SchoolClass = { id: string; name: string };

/** Compose the certified insights + simulations into a branded Markdown document. */
function insightsToDoc(insights: ClassInsight[], sims: Simulation[], schoolName: string | undefined, tr: (key: MessageKey) => string): BrandedDoc {
  const lines: string[] = [`# ${tr("school.insights.kernelInsightsTitle")}`];
  if (insights.length === 0) lines.push(tr("school.insights.noCertifiedYet"));
  for (const i of insights) {
    lines.push(`## ${i.className} · ${i.subjectName}`);
    lines.push(`- ${tr("school.overview.kpiAvgMastery")}: ${pct(i.avgMastery)}`);
    if (i.masteryTrend != null) lines.push(`- Trend: ${i.masteryTrend >= 0 ? "+" : ""}${Math.round(i.masteryTrend * 100)}%`);
    if (i.topGaps.length > 0) lines.push(`- ${tr("school.insights.topGapsLabel")}: ${i.topGaps.slice(0, 6).join(", ")}`);
    if (i.topRecommendation) lines.push(`- ${tr("school.insights.recommendationLabel")}: ${i.topRecommendation}`);
  }
  if (sims.length > 0) {
    lines.push(`# ${tr("school.insights.whatIfSimsHeading")}`);
    for (const s of sims) {
      const p = (s.parameters ?? {}) as { subjectName?: string; className?: string | null; addHours?: number; focus?: string | null };
      const r = (s.result ?? {}) as { projected_mastery_pct?: number | null; summary?: string };
      const head = `+${p.addHours ?? 0}${tr("school.insights.hoursPerWeekSuffix")} · ${p.subjectName ?? tr("school.insights.subjectFallback")}${p.className ? ` · ${p.className}` : ""}${p.focus ? ` · ${p.focus}` : ""}`;
      lines.push(`## ${head}`);
      if (r.projected_mastery_pct != null) lines.push(`- ${tr("school.insights.projectedMasteryLabel")}: ${r.projected_mastery_pct}%`);
      if (r.summary) lines.push(`- ${r.summary}`);
    }
  }
  return {
    brand: "bluestift",
    title: tr("school.insights.kernelInsightsTitle"),
    meta: new Date().toLocaleDateString(),
    audience: schoolName,
    body: lines.join("\n"),
  };
}

export function SchoolInsights({ schoolName }: { schoolName?: string }) {
  const { theme: t } = useAppTheme();
  const tr = useTranslate();
  const box = panelCard(t);
  const input = textInput(t);
  const btn = ctaButton(t);
  const [insights, setInsights] = useState<ClassInsight[]>([]);
  const [subjects, setSubjects] = useState<SchoolSubject[]>([]);
  const [classes, setClasses] = useState<SchoolClass[]>([]);
  const [sims, setSims] = useState<Simulation[]>([]);
  const [error, setError] = useState<string | null>(null);

  const [subjectId, setSubjectId] = useState("");
  const [classId, setClassId] = useState(""); // "" = all classes
  const [addHours, setAddHours] = useState(2);
  const [focus, setFocus] = useState("");
  const [busy, setBusy] = useState(false);

  useEffect(() => {
    (async () => {
      // Both requests fire together (the old code's Promise.all secretly ran
      // them one after another — `await fetch()` inside the array resolves
      // the first call before the second is ever issued) and are cached-first,
      // so re-opening this tab renders the last known insights instantly.
      const [ins, sim] = await Promise.all([
        getJsonCached<{ insights?: ClassInsight[]; subjects?: SchoolSubject[]; classes?: SchoolClass[] }>(
          "/api/school/insights",
          { cacheKey: "school:insights" },
        ),
        getJsonCached<{ simulations?: Simulation[] }>("/api/school/simulations", {
          cacheKey: "school:simulations",
        }),
      ]);
      if (!ins.data && !sim.data) {
        setError(tr("school.insights.loadFailed"));
        return;
      }
      if (ins.data) {
        setInsights(ins.data.insights ?? []);
        setSubjects(ins.data.subjects ?? []);
        setClasses(ins.data.classes ?? []);
        setSubjectId((ins.data.subjects?.[0] as SchoolSubject | undefined)?.id ?? "");
      }
      if (sim.data) setSims(sim.data.simulations ?? []);
    })();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  async function runSimulation(e: React.FormEvent) {
    e.preventDefault();
    if (busy || !subjectId) {
      if (!subjectId) setError(tr("school.reports.pickSubjectFirst"));
      return;
    }
    setBusy(true);
    setError(null);
    try {
      // The projection is generated by the LLM server-side, so the default 10s
      // budget is raised the same way the other LLM-backed POSTs in this app are.
      const res = await netFetch(
        "/api/school/simulations",
        {
          method: "POST",
          headers: { "content-type": "application/json" },
          body: JSON.stringify({ subjectId, classId: classId || null, addHours, focus }),
        },
        { timeoutMs: 65_000 },
      );
      const data = await res.json();
      if (!res.ok) {
        setError(data?.error ?? `Request failed (${res.status}).`);
        return;
      }
      setSims((s) => [data as Simulation, ...s]);
      invalidateCached("school:simulations");
    } catch {
      setError(tr("kernel.sim.runFailed"));
    } finally {
      setBusy(false);
    }
  }

  return (
    <div>
      {error && <p style={{ color: "#f87171" }}>{error}</p>}

      {/* Kernel insights */}
      <div style={box}>
        <div style={{ display: "flex", alignItems: "center", gap: "0.5rem" }}>
          <h3 style={{ margin: 0, flex: 1 }}>{tr("school.insights.kernelInsightsTitle")}</h3>
          {(insights.length > 0 || sims.length > 0) && (
            <DocumentActions doc={insightsToDoc(insights, sims, schoolName, tr)} compact shareable={false} personal />
          )}
        </div>
        <p style={{ opacity: 0.55, fontSize: "0.8rem", margin: "0.5rem 0 0.75rem" }}>
          {tr("school.insights.certifiedReadOnly")}
        </p>
        {insights.length === 0 ? (
          <p style={{ margin: 0, opacity: 0.65 }}>
            {tr("school.insights.noInsightsYetLong")}
          </p>
        ) : (
          insights.map((i) => (
            <div key={i.id} style={{ borderTop: `1px solid ${t.cardBorder}`, padding: "0.6rem 0" }}>
              <div style={{ display: "flex", gap: "0.5rem", alignItems: "baseline" }}>
                <strong style={{ flex: 1 }}>
                  {i.className} · {i.subjectName}
                </strong>
                <span style={{ opacity: 0.7, fontSize: "0.85rem" }}>{tr("school.insights.avgMasteryLower")} {pct(i.avgMastery)}</span>
                {i.masteryTrend != null && (
                  <span style={{ fontSize: "0.8rem", color: i.masteryTrend >= 0 ? "#22c55e" : "#f87171" }}>
                    {i.masteryTrend >= 0 ? "▲" : "▼"} {Math.abs(Math.round(i.masteryTrend * 100))}%
                  </span>
                )}
              </div>
              {i.topGaps.length > 0 && (
                <div style={{ fontSize: "0.85rem", opacity: 0.8, marginTop: "0.25rem" }}>
                  {tr("school.insights.topGapsLabel")}: {i.topGaps.slice(0, 4).join(", ")}
                </div>
              )}
              {i.topRecommendation && (
                <div style={{ fontSize: "0.85rem", opacity: 0.7, marginTop: "0.2rem" }}>💡 {i.topRecommendation}</div>
              )}
            </div>
          ))
        )}
      </div>

      {/* Simulation */}
      <div style={box}>
        <h3 style={{ marginTop: 0 }}>{tr("kernel.sim.title")}</h3>
        <p style={{ opacity: 0.55, fontSize: "0.8rem", margin: "0 0 0.75rem" }}>
          {tr("school.insights.simDescription")}
        </p>
        <form onSubmit={runSimulation} style={{ display: "flex", gap: "0.5rem", flexWrap: "wrap", alignItems: "center" }}>
          <select style={input} value={subjectId} onChange={(e) => setSubjectId(e.target.value)} disabled={busy}>
            {subjects.length === 0 && <option value="">{tr("school.team.noSubjectsOption")}</option>}
            {subjects.map((s) => (
              <option key={s.id} value={s.id}>
                {s.name}
              </option>
            ))}
          </select>
          <select style={input} value={classId} onChange={(e) => setClassId(e.target.value)} disabled={busy}>
            <option value="">{tr("school.archive.allClasses")}</option>
            {classes.map((c) => (
              <option key={c.id} value={c.id}>
                {c.name}
              </option>
            ))}
          </select>
          <label style={{ fontSize: "0.85rem", opacity: 0.7 }}>
            +
            <input
              type="number"
              min={0}
              max={20}
              value={addHours}
              onChange={(e) => setAddHours(Number(e.target.value))}
              style={{ ...input, width: 60, margin: "0 0.35rem" }}
              disabled={busy}
            />
            {tr("school.insights.hoursPerWeekSuffix")}
          </label>
          <input
            style={{ ...input, flex: 1, minWidth: 160 }}
            placeholder={tr("school.insights.focusPlaceholder")}
            value={focus}
            onChange={(e) => setFocus(e.target.value)}
            disabled={busy}
          />
          <button type="submit" style={{ ...btn, opacity: busy ? 0.7 : 1 }} disabled={busy}>
            {busy ? tr("school.insights.running") : tr("kernel.sim.run")}
          </button>
        </form>

        {sims.map((s) => (
          <SimulationCard key={s.id ?? s.createdAt} sim={s} />
        ))}
      </div>
    </div>
  );
}

function SimulationCard({ sim }: { sim: Simulation }) {
  const { theme: t } = useAppTheme();
  const tr = useTranslate();
  const p = sim.parameters as {
    subjectName?: string;
    className?: string | null;
    addHours?: number;
    focus?: string | null;
  };
  const r = (sim.result ?? {}) as {
    projected_mastery_pct?: number | null;
    confidence?: string;
    summary?: string;
    assumptions?: string[];
    risks?: string[];
  };
  return (
    <div style={{ border: `1px solid ${t.cardBorder}`, borderRadius: 12, padding: "0.75rem", marginTop: "0.75rem", background: t.cardBg }}>
      <div style={{ display: "flex", gap: "0.5rem", alignItems: "baseline" }}>
        <strong style={{ flex: 1 }}>
          +{p.addHours ?? 0}{tr("school.insights.hoursPerWeekSuffix")} · {p.subjectName ?? tr("school.insights.subjectFallback")}
          {p.className ? ` · ${p.className}` : ""}
          {p.focus ? ` · ${p.focus}` : ""}
        </strong>
        {r.projected_mastery_pct != null && (
          <span style={{ fontWeight: 700 }}>→ {r.projected_mastery_pct}%</span>
        )}
        {r.confidence && (
          <span style={{ fontSize: "0.75rem", opacity: 0.6 }}>{tr("school.insights.confidencePrefix")} {r.confidence}</span>
        )}
      </div>
      {r.summary && <p style={{ margin: "0.4rem 0 0", fontSize: "0.9rem", lineHeight: 1.5 }}>{r.summary}</p>}
      {r.risks && r.risks.length > 0 && (
        <p style={{ margin: "0.35rem 0 0", fontSize: "0.82rem", opacity: 0.7 }}>{tr("school.insights.risksPrefix")} {r.risks.join("; ")}</p>
      )}
    </div>
  );
}
