"use client";

import { useEffect, useState } from "react";
import type { BrandedDoc } from "@/lib/document";
import { useAppTheme } from "@/components/ui/theme";
import { netFetch, getJsonCached, invalidateCached } from "@/lib/net/client-fetch";
import { DocumentView } from "@/components/ui/document";
import { Modal } from "@/components/ui/modal";
import { ArtifactMenu } from "@/components/ui/artifact-menu";
import { panelCard, textInput, ctaButton, ghostButton } from "@/components/ui/forms";
import { useTranslate } from "@/components/ui/locale";
import type { MessageKey } from "@/lib/i18n";

type ReportItem = {
  id: string | null;
  title: string;
  scope: string | null;
  content: string;
  createdAt: string;
  archivedAt?: string | null;
};
type ClassOpt = { id: string; name: string };
type SubjectOpt = { id: string; name: string; code: string | null };
type Scope = "subject" | "class" | "school";

const SCOPE_LABEL_KEY: Record<string, MessageKey> = {
  school: "school.reports.wholeSchool",
  class: "school.reports.classReport",
  subject: "school.reports.subjectReport",
};

const SCOPE_ORDER: Scope[] = ["subject", "class", "school"];

export function SchoolReports({
  classes,
  schoolName,
  allowedScopes = SCOPE_ORDER,
}: {
  classes: ClassOpt[];
  schoolName?: string;
  /** Which report scopes this face may generate. A prof gets class-only. */
  allowedScopes?: Scope[];
}) {
  const { theme: t } = useAppTheme();
  const tr = useTranslate();
  const box = panelCard(t);
  const btn = ctaButton(t);
  const ghost = ghostButton(t);
  const select = textInput(t);
  // Keep the whole-school default for the admin; a single-scope face pins to it.
  const [scope, setScope] = useState<Scope>(
    allowedScopes.includes("school") ? "school" : allowedScopes[0] ?? "class",
  );
  const [classId, setClassId] = useState(classes[0]?.id ?? "");
  const [subjects, setSubjects] = useState<SubjectOpt[]>([]);
  const [subjectId, setSubjectId] = useState("");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [current, setCurrent] = useState<ReportItem | null>(null);
  const [reports, setReports] = useState<ReportItem[]>([]);

  useEffect(() => {
    (async () => {
      const apply = (data: { reports?: ReportItem[]; subjects?: SubjectOpt[] }) => {
        if (Array.isArray(data.reports)) setReports(data.reports);
        if (Array.isArray(data.subjects)) {
          setSubjects(data.subjects);
          setSubjectId((data.subjects[0] as SubjectOpt | undefined)?.id ?? "");
        }
      };
      // Cached first — best-effort either way, so a miss just leaves the
      // pickers to their defaults instead of showing an error for a list.
      const { data } = await getJsonCached<{ reports?: ReportItem[]; subjects?: SubjectOpt[] }>(
        "/api/school/reports",
        { cacheKey: "school:reports", onUpdate: apply },
      );
      if (data) apply(data);
    })();
  }, []);

  async function generate() {
    if (busy) return;
    if (scope === "class" && !classId) {
      setError(tr("school.reports.pickClassFirst"));
      return;
    }
    if (scope === "subject" && !subjectId) {
      setError(tr("school.reports.pickSubjectFirst"));
      return;
    }
    setBusy(true);
    setError(null);
    try {
      // The narrative is generated by the LLM server-side (non-streamed), so
      // this needs real headroom, not the default 10s.
      const data = await (
        await netFetch(
          "/api/school/reports",
          {
            method: "POST",
            headers: { "content-type": "application/json" },
            body: JSON.stringify({
              scope,
              classId: scope === "class" ? classId : undefined,
              subjectId: scope === "subject" ? subjectId : undefined,
            }),
          },
          { timeoutMs: 65_000 },
        )
      ).json();
      if (data.error) {
        setError(data.error);
        return;
      }
      const item = data as ReportItem;
      setCurrent(item);
      setReports((r) => [item, ...r]);
      invalidateCached("school:reports");
    } catch {
      setError(tr("school.reports.generateFailed"));
    } finally {
      setBusy(false);
    }
  }

  async function archiveReport(id: string, archived: boolean) {
    const res = await netFetch("/api/school/reports", {
      method: "PATCH",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({ id, action: archived ? "archive" : "unarchive" }),
    });
    const d = await res.json();
    // ArtifactMenu keeps its confirm dialog open and shows this rather than
    // silently doing nothing when the server refuses the action.
    if (!res.ok) throw new Error(d?.error);
    setReports((v) => v.map((r) => (r.id === id ? { ...r, archivedAt: d.archivedAt ?? null } : r)));
    invalidateCached("school:reports");
  }

  // Every generated report renders — and downloads — through the shared branded
  // document châssis (Bluestift logo + title + footer attribution). The report
  // body is Markdown, so DocumentView typesets it instead of dumping raw `#`.
  const docFor = (r: ReportItem): BrandedDoc => ({
    brand: "bluestift",
    title: r.title,
    meta: [tr(SCOPE_LABEL_KEY[r.scope ?? "school"] ?? "school.reports.wholeSchool"), new Date(r.createdAt).toLocaleDateString()].filter(Boolean).join(" · "),
    audience: schoolName,
    body: r.content,
  });

  return (
    <div>
      <div style={box}>
        <h2 style={{ fontSize: "1.1rem", margin: "0 0 0.75rem" }}>{tr("school.reports.generateTitle")}</h2>
        <div style={{ display: "flex", gap: "0.6rem", flexWrap: "wrap", alignItems: "center" }}>
          {allowedScopes.length > 1 && (
            <select style={select} value={scope} onChange={(e) => setScope(e.target.value as Scope)} disabled={busy}>
              {SCOPE_ORDER.filter((s) => allowedScopes.includes(s)).map((s) => (
                <option key={s} value={s}>
                  {s === "subject" ? tr("school.reports.bySubject") : s === "class" ? tr("school.reports.byClass") : tr("school.reports.wholeSchool")}
                </option>
              ))}
            </select>
          )}
          {scope === "class" && (
            <select style={select} value={classId} onChange={(e) => setClassId(e.target.value)} disabled={busy}>
              {classes.length === 0 && <option value="">{tr("school.team.noClassesOption")}</option>}
              {classes.map((c) => (
                <option key={c.id} value={c.id}>
                  {c.name}
                </option>
              ))}
            </select>
          )}
          {scope === "subject" && (
            <select style={select} value={subjectId} onChange={(e) => setSubjectId(e.target.value)} disabled={busy}>
              {subjects.length === 0 && <option value="">{tr("school.reports.noSubjectsYetOption")}</option>}
              {subjects.map((s) => (
                <option key={s.id} value={s.id}>
                  {s.name}
                </option>
              ))}
            </select>
          )}
          <button style={{ ...btn, marginLeft: "auto", opacity: busy ? 0.7 : 1 }} onClick={generate} disabled={busy}>
            {busy ? tr("tools.generating") : tr("tools.generate")}
          </button>
        </div>
        {error && <p style={{ color: "#f87171", margin: "0.75rem 0 0" }}>{error}</p>}
      </div>

      {/* Opened in a portalled modal so it escapes the shell and centres over the
          viewport (an in-tree fixed element gets trapped by shell transforms). */}
      {current && (
        <Modal onClose={() => setCurrent(null)} label={current.title}>
          <DocumentView
            {...docFor(current)}
            doc={docFor(current)}
            onClose={() => setCurrent(null)}
          />
        </Modal>
      )}

      {reports.length > 0 && (
        <div style={box}>
          <h3 style={{ marginTop: 0 }}>{tr("school.reports.pastReports")}</h3>
          {reports.map((r, i) => {
            const archived = !!r.archivedAt;
            return (
              <div
                key={r.id ?? i}
                style={{ display: "flex", gap: "0.5rem", alignItems: "center", padding: "0.35rem 0", opacity: archived ? 0.62 : 1 }}
              >
                <span style={{ flex: 1 }}>
                  {r.title}
                  {archived && (
                    <span style={{ opacity: 0.7, fontSize: "0.78rem" }}> · {tr("hist.archivedSection")}</span>
                  )}
                </span>
                <span style={{ opacity: 0.5, fontSize: "0.8rem" }}>{new Date(r.createdAt).toLocaleDateString()}</span>
                <button style={ghost} onClick={() => setCurrent(r)}>
                  {tr("school.roster.view")}
                </button>
                {r.id != null && (
                  <ArtifactMenu
                    theme={t}
                    itemLabel={r.title}
                    archived={archived}
                    // No hard delete for a report — see app/api/school/reports
                    // PATCH's doc comment: every report feeds the school's
                    // year-end archive purely by date, regardless of scope.
                    canDelete={false}
                    onArchive={(next) => archiveReport(r.id as string, next)}
                    onDelete={() => Promise.reject(new Error("reports cannot be deleted"))}
                  />
                )}
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
