// Shared, dependency-free document formatting used by BOTH the on-screen
// document châssis (`components/ui/document.tsx`) and the branded exporters
// (`lib/document.ts`), so a generated report reads the same on screen and in the
// downloaded PDF/TXT. Pure functions only — safe to import anywhere.

export type DocBrand = "bluestift" | "raya";

export type BrandInfo = {
  /** Human name used in the footer ("Generated by <name>…"). */
  name: string;
  /** Public logo path (in /public) drawn in the header. */
  logo: string;
  /** Accent hex for rules/headings on screen and in the PDF. */
  accent: string;
  /** Marketing site, shown as a link in the footer. */
  url: string;
};

/** Brand identity for a document. Schools/prof docs are Bluestift; Raya docs are Raya. */
export const DOC_BRANDS: Record<DocBrand, BrandInfo> = {
  bluestift: { name: "Bluestift", logo: "/bluestift-mark.png", accent: "#2f7fe0", url: "thebluestift.com" },
  raya: { name: "Raya", logo: "/raya-mark.png", accent: "#6366f1", url: "thebluestift.com" },
};

export type DocBlockType = "h1" | "h2" | "h3" | "p" | "li";
export type DocBlock = { type: DocBlockType; text: string };

/**
 * Minimal Markdown → block list. Reports come back as Markdown (`# Overview`,
 * `## Highlights`, `- item`, `**bold**`); we only need headings, list items and
 * paragraphs, so a per-line parser is enough — no dependency, no HTML.
 */
export function parseDoc(md: string): DocBlock[] {
  const blocks: DocBlock[] = [];
  for (const raw of md.replace(/\r\n/g, "\n").split("\n")) {
    const t = raw.trim();
    if (!t || t === "---" || t === "***") continue;
    if (t.startsWith("### ")) blocks.push({ type: "h3", text: t.slice(4).trim() });
    else if (t.startsWith("## ")) blocks.push({ type: "h2", text: t.slice(3).trim() });
    else if (t.startsWith("# ")) blocks.push({ type: "h1", text: t.slice(2).trim() });
    else if (/^[-*+]\s+/.test(t)) blocks.push({ type: "li", text: t.replace(/^[-*+]\s+/, "").trim() });
    else if (/^\d+\.\s+/.test(t)) blocks.push({ type: "li", text: t.replace(/^\d+\.\s+/, "").trim() });
    else blocks.push({ type: "p", text: t });
  }
  return blocks;
}

/** Drop inline emphasis markers (`**x**`, `__x__`, `*x*`) — for plain-text/PDF runs. */
export function stripInline(text: string): string {
  return text.replace(/\*\*(.+?)\*\*/g, "$1").replace(/__(.+?)__/g, "$1").replace(/\*(.+?)\*/g, "$1");
}

export type InlineSpan = { text: string; bold: boolean };

/** Split a line into bold/plain spans on `**…**` (for on-screen rendering). */
export function splitInline(text: string): InlineSpan[] {
  const spans: InlineSpan[] = [];
  const re = /\*\*(.+?)\*\*/g;
  let last = 0;
  let m: RegExpExecArray | null;
  while ((m = re.exec(text))) {
    if (m.index > last) spans.push({ text: text.slice(last, m.index), bold: false });
    spans.push({ text: m[1], bold: true });
    last = m.index + m[0].length;
  }
  if (last < text.length) spans.push({ text: text.slice(last), bold: false });
  return spans.length ? spans : [{ text, bold: false }];
}

/**
 * The one-line attribution shown at the foot of every document, on screen and in
 * exports: "Generated by Bluestift for <audience> · © 2026 Bluestift". The site
 * URL is appended separately so the exporter can make it a real link.
 */
export function footerLine(brand: DocBrand, audience?: string): string {
  const name = DOC_BRANDS[brand].name;
  const who = audience && audience.trim() ? ` for ${audience.trim()}` : "";
  return `Generated by ${name}${who} · © ${new Date().getFullYear()} Bluestift`;
}
