import { writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

/**
 * The site's faces, fetched once and compiled into the bundle.
 *
 * @remotion/google-fonts points @font-face at fonts.gstatic.com, so every tab
 * of every chunk of a render fetches them over the network — and a render that
 * needs the network for two hours is a render that fails when the line drops
 * for thirty seconds, which is exactly what happened. These are the same files,
 * inlined: the render is then entirely offline.
 *
 * Latin only. Every word in the film is Latin script, accents included
 * (Léa, Tomás, "Le passé composé"), and the latin subsets cover U+0000–00FF.
 *
 *   node scripts/fonts.mjs
 */
const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(here, "..");

// The four roles, and the weights the shots and the film actually set.
const FACES = [
  { family: "Space Grotesk", axis: "wght@500;600;700" },
  { family: "Inter", axis: "wght@400;500;600;700" },
  { family: "Instrument Serif", axis: "ital@1" },
  { family: "Geist Mono", axis: "wght@400;500;700;800" },
];
// Without a browser's user agent the API answers with TTF; with one, woff2.
const UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36";

const blocks = [];
let bytes = 0;
for (const { family, axis } of FACES) {
  const url = `https://fonts.googleapis.com/css2?family=${encodeURIComponent(family)}:${axis}&display=block`;
  const css = await (await fetch(url, { headers: { "user-agent": UA } })).text();
  // Each face arrives as "/* subset */ @font-face { … }" — keep the Latin ones.
  const faces = css.split("/*").slice(1);
  let kept = 0;
  for (const chunk of faces) {
    const subset = chunk.slice(0, chunk.indexOf("*/")).trim();
    if (subset !== "latin" && subset !== "latin-ext") continue;
    const rule = chunk.slice(chunk.indexOf("@font-face"));
    const src = rule.match(/url\((https:[^)]+\.woff2)\)/);
    if (!src) continue;
    const font = Buffer.from(await (await fetch(src[1], { headers: { "user-agent": UA } })).arrayBuffer());
    bytes += font.length;
    kept++;
    blocks.push(rule.replace(src[1], `data:font/woff2;base64,${font.toString("base64")}`).replace(/\s+/g, " ").trim());
  }
  console.log(`${family}: ${kept} faces`);
}

const out =
  `// Generated by scripts/fonts.mjs — do not edit.\n` +
  `/** The film's faces, inlined: a render needs no network. */\n` +
  `export const FONT_CSS = ${JSON.stringify(blocks.join("\n"))};\n\n` +
  `export const FONT_FAMILIES = {\n` +
  `  display: "Space Grotesk",\n  body: "Inter",\n  serif: "Instrument Serif",\n  mono: "Geist Mono",\n};\n`;
writeFileSync(path.join(root, "src", "generated", "fonts.ts"), out);
console.log(`${blocks.length} faces, ${Math.round(bytes / 1024)} KB → src/generated/fonts.ts (${Math.round(out.length / 1024)} KB)`);
