import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

/**
 * What the video borrows from the site, refreshed before every studio/render.
 *
 * The product shots are styled by app/globals.css — their keyframes, the
 * `pub-shot-*` classes, the font role properties. The video reads the same file
 * rather than a copy that would drift, minus the three `@tailwind` directives:
 * the shots use no utility classes, and Remotion has no PostCSS step for them.
 * The Bluestift mark comes along for the end card.
 */
const here = dirname(fileURLToPath(import.meta.url));
const repo = join(here, "..", "..");
const video = join(here, "..");

// Root-relative asset URLs (the hero clouds) are site pages' business, not the
// shots'; left in, the bundler tries to resolve them from this package and fails.
const css = readFileSync(join(repo, "app", "globals.css"), "utf8")
  .replace(/^@tailwind\s+\w+;\s*$/gm, "")
  .replace(/url\(\s*["']?\/[^)"']*["']?\s*\)/g, "none");
const cssTarget = join(video, "src", "generated", "site.css");
mkdirSync(dirname(cssTarget), { recursive: true });
writeFileSync(cssTarget, css);

// The marks: the end card's, and the ones the shots load by root-relative path
// (`/raya-mark.png`), which Remotion serves from this package's public/.
const marks = [
  "bluestift-mark.png",
  "bluestift-mark-dark.png",
  "raya-mark.png",
  "raya-mark-dark.png",
  "icon-512.png",
  "icon-raya-512.png",
  "hero-clouds-wide.png",
];
for (const mark of marks) {
  const target = join(video, "public", mark);
  mkdirSync(dirname(target), { recursive: true });
  copyFileSync(join(repo, "public", mark), target);
}
const brandTarget = join(video, "public", "brand", "bluestift-mark.png");
mkdirSync(dirname(brandTarget), { recursive: true });
copyFileSync(join(repo, "public", "bluestift-mark.png"), brandTarget);

/**
 * The same marks again, as data URIs compiled into the bundle.
 *
 * A render serves public/ over HTTP from a copy of it in a temp directory, and
 * halfway through a two-hour render that copy lost the files at its root: every
 * mark 404'd and Remotion cancelled the render (rightly — a missing image is a
 * wrong frame). The marks are a quarter of a megabyte in total and appear in
 * almost every scene, so they travel in the bundle instead. public/ still holds
 * them: the studio and the texture renders read them from there.
 */
const dataUri = (file) => `data:image/png;base64,${readFileSync(join(repo, "public", file)).toString("base64")}`;
const marksTs =
  `// Generated by scripts/sync-css.mjs — do not edit.\n` +
  `export const MARKS: Record<string, string> = {\n` +
  marks.map((m) => `  ${JSON.stringify(m)}: "${dataUri(m)}",\n`).join("") +
  `};\n\n/** A mark by file name, inlined; anything else stays a served file. */\n` +
  `export const mark = (file: string) => MARKS[file.replace(/^\\//, "")];\n`;
writeFileSync(join(video, "src", "generated", "marks.ts"), marksTs);

console.log(`site synced: globals.css (${Math.round(css.length / 1024)} KB), ${marks.length} marks (${Math.round(marksTs.length / 1024)} KB inlined)`);
