-- Translate a generated document once, for everyone, forever.
--
-- Every report, summary, quiz and simulation the product makes is produced in
-- one language and downloaded in one language. Offering four meant either
-- regenerating the document per language — paying the full generation each time,
-- with the source material back in context — or translating it on every click.
--
-- Keyed on a hash of the SOURCE CONTENT rather than on a document id, which is
-- what makes it worth having: two teachers exporting the same class report in
-- French pay for one call between them, and a summary of the same lesson
-- generated by thirty students in a class collapses to a single translation per
-- language. A document id would have given each of those its own cache miss.
--
-- Content-addressed, so it is also self-invalidating: change the report and the
-- hash changes, and the old row is simply never asked for again.
create table if not exists learning.document_translations (
  -- sha256 of `${title}\n${meta}\n${body}` of the SOURCE document.
  source_hash text not null,
  locale text not null,
  title text not null,
  meta text,
  body text not null,
  created_at timestamptz not null default now(),
  -- Cheap signal for pruning later: which translations are actually re-read.
  last_used_at timestamptz not null default now(),
  hits integer not null default 1,
  primary key (source_hash, locale)
);

comment on table learning.document_translations is
  'Content-addressed cache of translated exports. Keyed on a hash of the source document plus the target locale, so identical content anywhere in the product shares one translation. Nothing here is user-scoped: the rows hold generated study material, not personal data, and sharing them across users is the entire point.';

create index if not exists document_translations_last_used_idx
  on learning.document_translations (last_used_at);

-- No RLS policy and no grants: this table is written and read ONLY by the
-- service role, from app/api/documents/translate. A client that could read it
-- could enumerate other people's generated material by guessing hashes; a client
-- that could write it could poison what everyone else downloads.
alter table learning.document_translations enable row level security;
revoke all on learning.document_translations from anon, authenticated;
